//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean DrawEraseToggle
        {
            get
            {
                return SteamVR_Actions.default_DrawEraseToggle;
            }
        }
        
        public virtual SteamVR_Action_Boolean DrawEraseAction
        {
            get
            {
                return SteamVR_Actions.default_DrawEraseAction;
            }
        }
        
        public virtual SteamVR_Action_Pose ControllerPose
        {
            get
            {
                return SteamVR_Actions.default_ControllerPose;
            }
        }
    }
}
